### ISSUE TITLE
Support for encrypted backup

### ISSUE THREAD

**Issue by smortex** [xaque208/puppet-bacula#102]
Hello!

[Bacula supports signing / encrypting backups with the `PKI Signatures`, `PKI Encryption` and `PKI Keypair` settings.](http://www.bacula.org/5.0.x-manuals/en/main/main/Data_Encryption.html)

Unlike the name suggests, the `PKI Keypair` is expected to be a self-signed CA certificate (sic) + the associated private key. This was discovered after a lot of debugging trying to use the Puppet PKI to encrypt backups without success :cold_sweat: After checking the code, this is not possible without patching bacula…

Before submitting a Pull-Request, I would like to confirm with you that my plan for adding support for encryption is OK for you.  I also have a few questions.

## Parameters names

Two possibilities:

1. Use the settings name chosen by upstream, that is `pki_signature`, `pki_encryption` and `pki_keypair`, so basicaly `pki_*` while what it is used for has nothing to do with a PKI;
2. Use our own setting names, like `encrypt_backup`, `sign_backup`, etc.

While I usually consider that sticking to upstream's name is better,  since in this case the names are terrible and cause confusion, maybe an exception is wiser?

## Certificate / Key management

Since the self-signed certificate and the key have to be concatenated, we can either accept two parameters (certificate, key) and combine them, or a single parameter and it's the responsibility of the user to provide the right content.

AFAICR, it's possible to put only the self-signed certificate without the associated key, so this would allow this and may make the module a bit easier to use.

## Certificate / Key creation

Is it desirable to include a way to generate a key and a self-signed ca certificate on a node?  If yes, how do we suggest to the user to take a particular care with them (if the server explode, the user will need a copy of them in order to get back his data, so proper backup of these files is crucial, and exporting them to PuppetDB is a terrible idea :fearful: )?

**Comment by xaque208** [comment]
Hi!

The use of the term PKI here is a bit disappointing.  Best case would be that bacula starts accepting proper certs rather than self-signed.

I'm inclined to use the `pki_*` names mostly to allow users to look up what the values should be in the documentation, though, if we document the parameters in the classes well enough, then users should still be able to discover the actual values that arrive on disk if we use better names like `encrypt_backup_key_file` or some such.  I'd like to avoid the situation where users need to read templates in order to understand which option is getting into the configuration based on the parameter specification.  Otherwise, I think, as you say, flexibility here is probably wise.

For the key management portion, ugh.  I think for the module, probably the simplest approach would be to allow the user to specify a local file on each node, so `source => '/etc/ssl/keys/somefile.pem`, etc, and then we can use that file to put it where we need with the proper permissions.  How the file gets there is another matter.

The generation of the keys sounds like something that should be done outside of this module, but I don't really want to manage another thing to make that happen.  It would be interesting to generate keys in a central place and ship them out, rather that generate them on the node and then figure out how to backup the keys using a system that is not bacula!  Perhaps less ideal from a security perspective, but simpler to manage.  I'm thinking exported resource from the node to the bacula director or something here, but perhaps there is a more direct approach.

Can we generate a self-signed in an `openssl` one-liner?  Are you thinking an `exec` resource?  It's been a while since I was using self-signed certs.

**Comment by smortex** [comment]
Adding @neomilium to the loop so that he can share his view (as we co-maintain a Bacula infrastructure through Puppet).

The more I think about this, the more I think that the module should better use the same name as in Bacula and do not try to be too smart: Bacula already has a huge number of parameters, and while some of them have a confusing name, by not using custom names we are sure to not have problems in the future if they are renamed or new parameters with names clashing with our names are introduced…

I also share your view regarding key generation: it is part of another problem, and adding this to this module does not look right.  So I guess that we could simply let the module end-user manage everything:

```puppet
file { "/path/to/crt+key.pem":
  source => 'whatever://crt+key.pem',
}
# or something that generates this file with exec / concat / a dedicated module
# since the user had to make a decision, he should be aware of the need of keeping this data secure.

class { 'bacula::client':
  # [...]
  pki_encryption => true,
  pki_signatures => true,
  pki_keypair    => "/path/to/crt+key.pem",
}
```

That way looks dead simple, or: _How I learned to stop over-engineering workaround to weird Bacula parameters name and used them without worrying_.

**Comment by xaque208** [comment]
Support was added in `5.2.0`.  Marking resolved.
