### ISSUE TITLE
future maintenance and collaboration

### ISSUE THREAD

**Issue by anarcat** [xaque208/puppet-bacula#136]
This module is one out of [about 10 bacula modules on Puppet Forge](https://forge.puppet.com/modules?q=bacula). It is [first in rank](https://forge.puppet.com/modules?utf-8=%E2%9C%93&page_size=25&sort=rank&q=bacula) and [second in downloads](https://forge.puppet.com/modules?q=bacula&page_size=25&sort=downloads) which makes it an interesting candidate for a "ad-hoc standard" bacula module for Puppet.

When you first released this module, the [Vox Populi/Puppetlabs module](https://github.com/voxpupuli/puppet-bacula/) already existed. What motivated you to start a new one? How does it compare with the other implementations?

Is there a possibility of converging efforts towards a single module that everyone contributes to?

Thank you for your work!

**Comment by anarcat** [comment]
Note that I have filed a similar issue in the other two module, in the hope some future collaboration will emerge (https://github.com/NTTCom-MS/eyp-bacula/issues/9 https://github.com/voxpupuli/puppet-bacula/issues/47).

**Comment by xaque208** [comment]
Hello, and thank you for your interest in the module.

I can't honestly compare the two modules, since I've not read the code of the VoxPupuli module in quite a while.  What I can tell you, is that module was started by James Tunrbull and somebody named root to be used in production at Puppet Labs, and I was on the team responsible for the infrastructure of the company.  I can't remember the timeline so well, but this module might predate the Forge itself.  You can see the commit history if you'd like.

It was a few years later that what is now the VoxPupuli was started, out of a Project Empathy where Product Managers could learn and experience the pain that Puppet users felt when developing and publishing modules.  The natural result was that the Bacula module was first to be published to the Forge since there was not already one present.

The Operations team later decided to use a different backup solution, and so I moved this module and its history in to the public with my team's permission.  I still use it today, as do a few others, though I do not know how many.  This module solves all of my Bacula deployment scenarios and I've relied on it for years, though I am no longer with the company.

I haven't too much a mind to build the "One True $x Module".  The modules under my name are still in use by me, and I have every intention of continuing to use them with a few exceptions.  I certainly embrace and appreciate all the contributions I've received over the years, and its a real pleasure to work the authors.  I'm just happy to have people get use out of the modules.

With that in mind, what is your goal?  How can I help future maintenance and collaboration?

**Comment by anarcat** [comment]
Hi!

Thanks for your detailed reply. It does shed some light on the project... My goal is simply to replace a custom module we use locally for Bacula for something that is community maintained. I want to pick the best one, naturally (or more accurately the one that is the best fit for our use case), so I was curious to hear how the different modules compare.

Since I want to avoid work duplication as well, I figured I would enquire as to how it would be possible to collaborate across modules, but I understand this is a much harder problem. :)

Thanks for your feedback, I think this ticket can be closed and kept as a future reference...

(Also note that my report originally said this module was third in rank and download, that was incorrect: it's currently *first* in rank and second in download, slightly behind the puppetlabs one, which doesn't seem to be maintained. So your module is actually a prime choice for a standard, as I said...)

**Comment by xaque208** [comment]
We'd welcome any contributions, and thanks for your interest.  Cheers.

**Comment by smortex** [comment]
@anarcat, to complete what @xaque208 said with some end-user (and now contributor) feedback, I have been using this bacula module for ~2 years now.  I chose this one because it looked-like the most feature-complete of those available, and had support for nearly everything we needed.

At that time we where not using PuppetDB yet and it was quite a concern that we had to look into this in order to use the module.  We soon discovered how smart it was to rely on it and the good design of the module helped us open our mind to new use cases for PuppetDB.

We first hacked our local modifications for our use cases in an internal repo, and soon cleaned-up these changes and upstreamed them to avoid managing them ourself.  @xaque208 has been really helpful and responsive in this process, and it's a pleasure to work with him to bring in new features and bug fixes.

The consequence is that when we needed a module for managing something, we look especially into those from **zleslie** on the forge because we ended up discovering they have a particularly high quality and wise design, and it's a pleasure to work with them, and they bring awesome features we did not even though about but cannot live without now that we have seen them (I am looking at you, managing ssh's known_hosts file through PuppetDB :wink:)
